import 'package:quran_app/colors/images.dart';
import 'package:quran_app/colors/string.dart';

const prayerListImages = [icFajer, icDuhar, icAsar, icMagrib, icIsha];
var prayerNameList = [fajar, duhar, asar, magrib, isha];

//Explore more icons List
const iconList = [
  icKatmeyNabuat,
  icDuhannds,
  icQibla,
  icTasbi,
  icNamesofallah,
  icShahad,
  icMoon
];
const iconsLisName = [
  '    Finality of\n  prophethood',
  'Daily Dua',
  'Qibla\n Direction',
  'Tasbih\n Counter',
  'Asma ul\n Husna',
  'Shadat',
  'Hadith'
];
//---------> Name of Allah in Arabic <---------------
const allahNameList = [
  "الرَّحْمَنُ",
  "الرَّحِيمُ",
  "الْمَلِكُ",
  "الْقُدُّوسُ",
  "السَّلاَمُ",
  "الْمُؤْمِنُ",
  "الْمُهَيْمِنُ",
  "الْعَزِيزُ",
  "الْجَبَّارُ",
  "الْمُتَكَبِّرُ",
  "الْخَالِقُ",
  "الْبَارِئُ",
  "الْمُصَوِّرُ",
  "الْغَفَّارُ",
  "الْقَهَّارُ",
  "الْوَهَّابُ",
  "الرَّزَّاقُ",
  "الْفَتَّاحُ",
  "الْعَلِيمُ",
  "الْقَابِضُ",
  "الْبَاسِطُ",
  "الْخَافِضُ",
  "الرَّافِعُ",
  "الْمُعِزُّ",
  "الْمُذِلُّ",
  "السَّمِيعُ",
  "الْبَصِيرُ",
  "الْحَكَمُ",
  "الْعَدْلُ",
  "اللَّطِيفُ",
  "الْخَبِيرُ",
  "الْحَلِيمُ",
  "الْعَظِيمُ",
  "الْغَفُورُ",
  "الشَّكُورُ",
  "الْعَلِيُّ",
  "الْكَبِيرُ",
  "الْحَفِيظُ",
  "الْمُقِيتُ",
  "الْحَسِيبُ",
  "الْجَلِيلُ",
  "الْكَرِيمُ",
  "الرَّقِيبُ",
  "الْمُجِيبُ",
  "الْوَاسِعُ",
  "الْحَكِيمُ",
  "الْوَدُودُ",
  "الْمَجِيدُ",
  "الْبَاعِثُ",
  "الشَّهِيدُ",
  "الْحَقُّ",
  "الْوَكِيلُ",
  "الْقَوِيُّ",
  "الْوَلِيُّ",
  "الْمَتِينُ",
  "الْحَمِيدُ",
  "الْمُحْصِيُ",
  "الْمُبْدِئُ",
  "الْمُعِيدُ",
  "الْمُحْيِي",
  "الْمُمِيتُ",
  "الْحَيُّ",
  "الْقَيُّومُ",
  "الْوَاجِدُ",
  "الْمَاجِدُ",
  "الْوَاحِدُ",
  "الْأَحَدُ",
  "الصَّمَدُ",
  "الْقَادِرُ",
  "الْمُقْتَدِرُ",
  "الْمُقَدِّمُ",
  "الْمُؤَخِّرُ",
  "الأَوَّلُ",
  "الْآخِرُ",
  "الظَّاهِرُ",
  "الْبَاطِنُ",
  "الْوَالِي",
  "الْمُتَعَالِي",
  "الْبَرُّ",
  "التَّوَابُ",
  "الْمُنْتَقِمُ",
  "الْعَفُوُّ",
  "الرَّؤُوفُ",
  "مَالِكُ الْمُلْكِ",
  "ذُو الْجَلاَلِ وَالْإِكْرَامِ",
  "الْمُقْسِطُ",
  "الْجَامِعُ",
  "الْغَنِيُّ",
  "الْمُغْنِي",
  "الْمَانِعُ",
  "الضَّارُّ",
  "النَّافِعُ",
  "النُّورُ",
  "الْهَادِي",
  "الْبَدِيعُ",
  "الْبَاقِي",
  "الْوَارِثُ",
  "الرَّشِيدُ",
  "ٱلْصَّبُورُ"
];
// ---------------> Names of ALlah in English   <-----------------------
const List<String> allahNameListEnglish = [
  "Ar-Rahman",
  "Ar-Raheem",
  "Al-Malik",
  "Al-Quddus",
  "As-Salam",
  "Al-Mu'min",
  "Al-Muhaymin",
  "Al-Aziz",
  "Al-Jabbar",
  "Al-Mutakabbir",
  "Al-Khaliq",
  "Al-Bari'",
  "Al-Musawwir",
  "Al-Ghaffar",
  "Al-Qahhar",
  "Al-Wahhab",
  "Ar-Razzaq",
  "Al-Fattah",
  "Al-Alim",
  "Al-Qabid",
  "Al-Basit",
  "Al-Khafid",
  "Ar-Rafi'",
  "Al-Mu'izz",
  "Al-Mudhill",
  "As-Sami'",
  "Al-Basir",
  "Al-Hakam",
  "Al-Adl",
  "Al-Latif",
  "Al-Khabir",
  "Al-Halim",
  "Al-Azim",
  "Al-Ghafur",
  "Ash-Shakur",
  "Al-Ali",
  "Al-Kabir",
  "Al-Hafiz",
  "Al-Muqit",
  "Al-Hasib",
  "Al-Jalil",
  "Al-Karim",
  "Ar-Raqib",
  "Al-Mujib",
  "Al-Wasi'",
  "Al-Hakim",
  "Al-Wadud",
  "Al-Majid",
  "Al-Ba'ith",
  "Ash-Shahid",
  "Al-Haqq",
  "Al-Wakil",
  "Al-Qawiyy",
  "Al-Wali",
  "Al-Matin",
  "Al-Hamid",
  "Al-Muhsi",
  "Al-Mubdi",
  "Al-Mu'id",
  "Al-Muhyi",
  "Al-Mumit",
  "Al-Hayy",
  "Al-Qayyum",
  "Al-Wajid",
  "Al-Majid",
  "Al-Wahid",
  "Al-Ahad",
  "As-Samad",
  "Al-Qadir",
  "Al-Muqtadir",
  "Al-Muqaddim",
  "Al-Mu'akhkhir",
  "Al-Awwal",
  "Al-Akhir",
  "Adh-Dhahir",
  "Al-Batin",
  "Al-Wali",
  "Al-Muta'ali",
  "Al-Barr",
  "At-Tawwab",
  "Al-Muntaqim",
  "Al-Afuww",
  "Ar-Ra'uf",
  "Malikul-Mulk",
  "Dhul-Jalali Wal-Ikram",
  "Al-Muqsit",
  "Al-Jami'",
  "Al-Ghani",
  "Al-Mughni",
  "Al-Mani'",
  "Ad-Darr",
  "An-Nafi'",
  "An-Nur",
  "Al-Hadi",
  "Al-Badi'",
  "Al-Baqi",
  "Al-Warith",
  "Ar-Rashid",
  "AS-Saboor"
];
// ----------> Names of Allah Meaning <--------------
const List<String> allahNameMeanings = [
  "The Most Gracious",
  "The Most Merciful",
  "The King",
  "The Most Holy",
  "The Source of Peace",
  "The Guardian of Faith",
  "The Protector",
  "The Mighty",
  "The Compeller",
  "The Supreme",
  "The Creator",
  "The Maker",
  "The Fashioner",
  "The Forgiver",
  "The Subduer",
  "The Bestower",
  "The Provider",
  "The Opener",
  "The All-Knowing",
  "The Restrainer",
  "The Expander",
  "The Abaser",
  "The Exalter",
  "The Honorer",
  "The Humiliator",
  "The All-Hearing",
  "The All-Seeing",
  "The Judge",
  "The Just",
  "The Subtle One",
  "The All-Aware",
  "The Forbearing",
  "The Magnificent",
  "The Forgiving",
  "The Appreciative",
  "The Exalted",
  "The Great",
  "The Guardian",
  "The Sustainer",
  "The Reckoner",
  "The Majestic",
  "The Generous",
  "The Watchful",
  "The Responder",
  "The All-Encompassing",
  "The Wise",
  "The Loving",
  "The Glorious",
  "The Resurrector",
  "The Witness",
  "The Truth",
  "The Trustee",
  "The Powerful",
  "The Protecting Friend",
  "The Firm",
  "The Praiseworthy",
  "The All-Enumerating",
  "The Originator",
  "The Restorer",
  "The Giver of Life",
  "The Bringer of Death",
  "The Ever-Living",
  "The Self-Existing",
  "The Finder",
  "The Glorious",
  "The One",
  "The Unique",
  "The Eternal",
  "The All-Powerful",
  "The Determiner of All Things",
  "The Expediter",
  "The Delayer",
  "The First",
  "The Last",
  "The Manifest",
  "The Hidden",
  "The Governor",
  "The Most Exalted",
  "The Source of Goodness",
  "The Acceptor of Repentance",
  "The Avenger",
  "The Pardoner",
  "The Compassionate",
  "The Owner of All Sovereignty",
  "The Possessor of Majesty and Honor",
  "The Equitable",
  "The Gatherer",
  "The Self-Sufficient",
  "The Enricher",
  "The Withholder",
  "The Distresser",
  "The Bestower of Benefits",
  "The Light",
  "The Guide",
  "The Incomparable",
  "The Everlasting",
  "The Inheritor",
  "The Righteous Teacher",
  "The Forbearing"
];

//-------------------> Hadit list with duaname, dua in arabic and english translation <-----------------
List<String> duaName = [
  "THE PRAYER AT THE TIME OF SLEEPING",
  "THE PRAYER AT THE TIME OF SEEING A MUSLIM SMILING",
  "THE PRAYER FOR THANKING SOMEONE WHO DOES A FAVOR",
  "THE PRAYER AT THE TIME OF RETURN OF A LOAN",
  "THE PRAYER AT THE TIME OF FEELING ANGER",
  "THE PRAYER AT THE TIME OF RECEIVING A GIFT",
  "THE PRAYER AFTER SNEEZING",
  "THE PRAYER AT THE TIME OF TRAVELLING",
  "THE PRAYER AT THE TIME OF STARTING ANY NEW PIECE OF WORK ",
  "THE PRAYER AT THE TIME OF SEEING OFF A TRAVELER",
  "THE PRAYER AFTER AWAKING FROM SLEEP",
  "THE PRAYER AT THE TIME OF ENTERING A CITY",
  "THE PRAYER AT THE TIME OF SEEING THE NEW MOON",
  "THE PRAYER AT THE TIME SEEING SOMEONE IN DIFFICULT",
  "THE PRAYER AT THE TIME SEEING THE MOON",
  "THE PRAYER FOR ASKING FOR RAIN",
  "THE PRAYER AT THE TIME OF ITS RAINING",
  "THE PRAYER AT THE TIME OF ENTERING MARKET",
  "THE PRAYER BEFORE ENTERING THE TOILT",
  "THE PRAYER BEFORE STARTING ABLUTION",
  "PRAYER BEFORE PERFORMING ABLUTAION",
  "THE PRAYER DURING PERFORMING ABLUTATION",
  "PRAYER AT THE TIME OF ENTERING MOSQUE",
  "PRAYER AFTER NAMAZ FAJAR",
  "PRAYER AFTER LEAVING THE MAJLIS",
  'PRAYER FOR LEAVING THE MASJID'
];
List<String> duaArabic = [
  'اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَاحْيى',
  'أَضْحَكَ اللهُ سِنَّكَ',
  'جَزَاكَ اللهُ خَيْرًا',
  'اللهم اكفني بِمَلاً يكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
  'أعُوذُ بِاللهِ مِنَ الشَّيْطَنِ الرَّحِيمِ',
  'بَارَكَ اللهُ فِي أَهْلِكَ وَمَالِكَ ',
  'الحمدُ للهِ',
  'استودع الله دِينَكَ وَا مَا لَتَكَ وَخَوْا لِيُمَعَمَلِكَ',
  'استودِعُكَ اللَّهَ الَّذِي لَا تُخَيبُ أَوْ لَا تُطَيعُ',
  'استودِعُكَ اللَّهَ الَّذِي لَا تُخَيبُ أَوْ لَا تُطَيعُ',
  'ما أمَاتَنَا وَالَيْهِ النشور',
  'اَللّٰہُ اَکْبَرُ، اَللّٰہُمَّ اَھِلَّہ عَلَیْنَابِالْیُمْنِ وَالْاِیْمَانِ وَالسَّلَامَةِ وَالْاِسْلَامِ ،رَبِّیْ وَرَبُّکَ اللّٰہُ ۔',
  'اَلْحَمْدُ لِلّٰہِ الَّذِیْ عَافَانِیْ مِمَّاابْتَلاَ کَ بِہ وَفَضَّلَنِیْ عَلٰی کَثِیْرٍ مِّمَّنْ خَلَقَ تَفْضِیْلاً۔',
  'أَعُوذُ بِاللَّهِ مِنْ شَرِّ هَذَا لغاسِق',
  'اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
  'اللَّهُمَّ أَغِثْنَا',
  'اللَّهُمَّ صَيِّبَاً نَافِعَاً',
  'بِسْمِ اللّٰہِ، اَللّٰھُمَّ اِنِّیْ اَسْئَلُکَ خَیْرَ ھٰذِہِ السُّوْقِ وَخَیْرَمَافِیْھَاوَاَعُوْذُبِکَ مِنْ شَرِّ ھَا وَشَرِّمَافِیْھَااَللّٰھُمَّ اِنِّیْ اَعُوذُبِکَ اَنْ اُصِیْبَ فِیْھَایَمِیْنًا فَاجِرَةً اَوْصَفْقَةً خَاسِرَةً۔',
  'اَللّٰہُمَّ اِنِّیْ اَعُوْذُبِکَ مِنَ الْخُبُثِ وَالْخَبَآئِثِ۔',
  'بِسْمِ اللّٰہِ الرَّحْمٰنِ الرَّحِیْمِ۔',
  'اَلْحَمْدُ لِلّٰہِ الَّذِیْ بِنِعْمَتِہ تَتِمُّ الصَّالِحَاتُ',
  'اَللّٰھُمَّ اغْفِرْلِیْ ذَنْبِی وَوَسِّعْ لِیْ فِیْ دَارِیْ وَبَارِکْ لِیْ فِیْ رِزْقِیْ ۔',
  'اَللّٰہُمَّ افْتَحْ لِیْ اَبْوَابَ رَحْمَتِکَ۔',
  'اَللّٰہُمَّ اِنِّیْ اَسْئَلُکَ رِزْقًا طَیِّبًا وَّعِلْمًا نَّافِعًاوَّعَمَلًا مُّتَقَبَّلاً ۔',
  'سُبْحَانَکَ اللّٰھُمَّ وَبِحَمْدِکَ اَشْہَدُاَلَّااِلٰہَ اِلَّااَنْتَ اَسْتَغْفِرُکَ وَاَتُوْبُ اِلَیْکَ ۔',
  'اَللّٰھُمَّ اِنِّیْ اَسْئَلُکَ مِنْ فَضْلِکَ ۔'
];
List<String> duaEnglis = [
  "O Allah (Almighty) I live and die in your name.",
  "May Allah Almighty keep you smiling.",
  "May Allah Almighty give you good recompense (for doing a favor).",
  "May Allah Almighty give me enough, give me your Halal provision and save me from Haraam provision and do not make me needyof anyone except yourself by your grace.",
  "I seek the refuge of Allah Almighty from the rejected Shetan.",
  "May Allah Almighty Bless your family.",
  "All praise onto Allah Almighty.",
  "I hand over your religoion and what you have given in trust and the outcome of deed to Allah Azzawajal.",
  "It's movement and it's stopping is in the name of Allah Azzawajal undoubtedly my Lord Azzawajal is forgiving, affectionate.",
  "I hand you over to Allah Azzawajal who does not waste what is given in his trust.",
  "All praise onto Allah (Almighty) Who granted us life after death (sleep) we are to return to him.",
  "O Allah Azzawajal make this moon come out on us with blessings and with Iman and peace and Islam and make it come out with the ability of that thing which pleases you and that you like, (O moon of the first night my and your Lord is Allah Azzawajal).",
  "All praise belongs to Allah who has saved me from such a condition which is afflicted on you and favoured me over many creations. The virtues of this dua is that the reciter will be saved from the difficulties he has seen.",
  "I seek the refuge of Allah Azzawajal from the badness of this that darkness.",
  "O Allah Azzawajal as you made my outward appearance good make my character good too.",
  "O Allah, listen to our plea (request).",
  "O Allah make it plentiful and beneficial.",
  "I entered in the name of Allah, I seek refuge in You (Allah) for the good in the bazaar and for the good of what is in it (the bazaar). O Allah, I seek refuge in you from false oaths and deception in transaction",
  "O Allah (Almighty) I seek your refuge from impure Jinnat (male and female).",
  "In the name of Allah, the most merciful, the most kind.",
  "Praise to Allah by whose grace good deeds are completed.",
  "O Allah Azzawajal forgive me and give me abundance and blessing in my house and grant me abundance in my livlihood.",
  "O Allah, open the doors of mercy",
  "O Allah, I ask You for knowledge which is beneficial and sustenance which is good, and deeds which are acceptable.",
  'O Allah, You are pure, I praise You and testify that there is none worthy of worship besides You. I seek forgiveness and pardon from You". If there was good talk in the gathering, this dua will seal it and if there was futile and vain talk, then this dua will recompense for it.',
  "O Allah, verily i seek from you, your bounty."
];
